services:
  libvirt-exporter:
    image: libvirt-exporter:latest 
    container_name: libvirt-exporter
    ports:
      - "9177:9177"
    networks:
      - npm_net
    # environment:
    #  - key:"value"
    labels:
      homepage.group: "Grafana"
      homepage.name: "libvirt exporter"
      homepage.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/prometheus-node-exporter.svg"
      homepage.href: "http://192.168.0.160:3000/"
      homepage.description: "libvirt exporter for Prometheus"
    volumes:
      - /var/run/libvirt:/var/run/libvirt
    restart: unless-stopped

networks:
  npm_net:
    external: true
